# use vi mode instead of emacs
set -o vi

# aliases
alias l="ls -alhF"
alias la="ls -a"

alias sctl="systemctl"
alias bingvpn="sudo openconnect buvpn.binghamton.edu --user rfanchi1"

# nix aliases
alias switch="sudo nixos-rebuild --flake .#nixos-desktop switch"
alias n="nix-shell -p"

# ssh to binghamton remotes, param is number of machine to connect to
sshbu() {
    [[ ${1} =~ ^[0-9]*$ ]] || {
        echo "Usage: ${FUNCNAME[0]} <RemoteID: Unsigned | None>"
        return 1
    }
    local machine_num=""
    [[ $# -ge 1 ]] && machine_num="$(printf "%02d" "${1}")"
    ssh "rfanchi1@remote${machine_num}.cs.binghamton.edu"
}

# commit all changes in current repo, copy latest hash to clipboard
gitall() {
    git add -A || return
    git commit -m "$*" || return
    git push || return
    echo "Latest git hash:"
    git rev-parse HEAD
}
